---
title: "ANALISIS G4"
author: "G4"
format:
  html:
    toc: true
    toc-expand: true
    toc-depth: 4
    toc-location: left
    number-sections: true
    self-contained: true
    code-fold: true
    output-file: "ESM"
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
  echo: true
---

# Project Setup

```{r}
#| label:  setup

source('https://inkaverse.com/setup.r')
```

# Data import

```{r}
gs <- "https://docs.google.com/spreadsheets/d/1QziIXGOwb8cl3GaARJq6Ez6aU7vND_UHKJnFcAKx0VI/edit?gid=137089581#gid=137089581" %>% 
  as_sheets_id()

prosopis <- gs %>% 
  range_read(ss = .,sheet = "prosopis")
```

# Indice de germinacion
```{r}
gsm <- ger_summary(
  factors = c("rep", "nacl", "temp"), 
  SeedN = "seeds",                    
  evalName = "d",                     
  cumulative = FALSE,                 
  data = fb                           
)




# Imprimir el resultado en la consola
print(gsm)
```

#porcentaje de germinación 

```{r}
library(knitr)

# ANOVA
av <- aov(mgt ~ nacl * temp + rep, data = gsm)

# Prueba de comparación de medias (SNK)
mc_mgt <- ger_testcomp(
  aov  = av,
  comp = c("nacl", "temp"),
  type = "snk"
)

# Tabla
mc_mgt$table |> kable(caption = "Mean germination time comparison")
```

 
# Grafico PORCENTAJE DE GERMINACION

```{r}
gsm <- ger_summary(
  factors = c("rep", "nacl", "temp"), 
  SeedN = "seeds",                    
  evalName = "d",                     
  cumulative = FALSE,                 
  data = fb                           
)

# Imprimir el resultado en la consola
print(gsm)
```

# TIEMPO MEDIO DE GERMINACION 
```{r}
gsm |>
  mutate(
    nacl = factor(nacl),
    temp = factor(temp, labels = c("25°C", "30°C", "35°C", "40°C"))
  ) |>
  summarise(
    mean_mgt = mean(mgt),
    se_mgt   = sd(mgt) / sqrt(n()),
    .by = c(nacl, temp)
  ) 
```

```{r}
library(knitr)

# ANOVA
av <- aov(mgt ~ nacl * temp + rep, data = gsm)

# Prueba de comparación de medias (SNK)
mc_mgt <- ger_testcomp(
  aov  = av,
  comp = c("nacl", "temp"),
  type = "snk"
)

# Tabla
mc_mgt$table |> kable(caption = "Mean germination time comparison")
```

# GRAFICO TIEMPO MEDIO DE GERMINACION
```{r}
gsm |>
  mutate(
    nacl = factor(nacl),
    temp = factor(temp, labels = c("25°C", "30°C", "35°C", "40°C"))
  ) |>
  summarise(
    mean_mgt = mean(mgt),
    se_mgt   = sd(mgt) / sqrt(n()),
    .by = c(nacl, temp)
  ) |>
  ggplot(aes(x = nacl, y = mean_mgt, fill = temp)) +
  geom_col(position = position_dodge(0.8), width = 0.7) +
  geom_errorbar(
    aes(ymin = mean_mgt - se_mgt, ymax = mean_mgt + se_mgt),
    position = position_dodge(0.8),
    width = 0.25
  ) +
  labs(
    x        = "Concentración de NaCl (g/L)",
    y        = "Tiempo medio de germinación (días)",
    fill     = "Temperatura",
    title    = "Tiempo medio de germinación de Prosopis",
    subtitle = "Media ± error estándar"
  ) +
  theme_bw() +
  theme(
    legend.position = "right",
    plot.title      = element_text(face = "bold")
  )
```

# CALCULO PARA PCA
```{r}
library(FactoMineR)
library(factoextra)

pca_data <- gsm |>
  dplyr::mutate(
    nacl = factor(nacl),
    temp = factor(temp)
  )

pca_res <- pca_data |>
  dplyr::select(grp, mgt, mgr, gsp, unc, syn, vgt, sdg, cvg) |>
  PCA(scale.unit = TRUE, graph = FALSE)

fviz_pca_biplot(
  pca_res,
  geom.ind     = "point",
  col.ind      = pca_data$nacl,
  shape.ind    = pca_data$temp,
  addEllipses  = TRUE,
  ellipse.level = 0.95,
  col.var      = "black",
  repel        = TRUE,
  legend.title = list(color = "NaCl (g/L)", shape = "Temp (°C)"),
  title        = "PCA - Índices de germinación de Prosopis"
) +
  theme_bw()

```

#GRAFICO para PCA
```{r}
fviz_pca_biplot(
  pca_res,
  geom.ind      = "point",
  col.ind       = pca_data$nacl,
  shape.ind     = pca_data$temp,
  addEllipses   = TRUE,
  ellipse.level = 0.95,
  col.var       = "black",
  repel         = TRUE,
  legend.title  = list(color = "NaCl (g/L)", shape = "Temp (°C)"),
  title         = "PCA - Índices de germinación de Prosopis"
) +
  theme_bw()
```



